pub const APP_NAME: &str = "NK";
pub const BIND_ADDR_IPV4: &str = "0.0.0.0";
pub const BIND_ADDR_IPV6: &str = "::";
pub const BIND_PORT: u16 = 0;
pub const MAX_PACKET_SIZE: usize = 512;
pub const LOGFILE_DIR: &str = ".";
pub const LOGFILE_NAME: &str = "nk.log";
pub const PING_MSG: &str = "!!! Death to the demoness, Allegra Geller! Death to eXistenZ !!!";
pub const BUFFER_SIZE: usize = 100;
